name: vana_sky_stash
description: "A simple shopping list app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+alpha.2

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.4.0
  sqflite: ^2.4.1
  flutter_secure_storage: ^10.0.0-beta.4

  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.5
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  country_flags: ^3.2.0
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^8.1.3
  url_launcher: ^6.3.1
  path: ^1.9.0

flutter_launcher_icons:
    android: true
    ios: true
    windows:
      generate: true
      image_path: "assets/app_icon.png"
      icon_size: 48
    linux: true
    image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
