name: vana_sky_stash
description: "A simple shopping list app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  flutter_secure_storage:
    git: https://github.com/juliansteenbakker/flutter_secure_storage 
    ref: master

  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.5
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  country_flags: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
