name: Flutter Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Get dependencies
        run: flutter pub get

      - name: Build for windows
        run: flutter build windows

