name: Flutter Build

on:
  push:
    branches:
      - develop

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Get flutter deps
        run: flutter pub get

      - name: Build for windows
        run: flutter build windows

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Get makedeps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++  libgtk-3-dev libsecret-1-dev

      - name: Get flutter deps
        run: flutter pub get

      - name: Build for linux
        run: flutter build linux

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkoit@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master' 

      - name: Get flutter deps
        run: flutter pub get 

      - name: Build for android
        run: flutter build apk
