name: Flutter Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ 

      - name: Get dependencies
        run: flutter pub get

      - name: Build for linux
        run: flutter build linux

      - name: Build for android
        run: flutter build apk
