name: Flutter Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ windows, linux ]
        include:
          - platform: windows
            os: windows-latest
          - platform: linux
            os: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.6.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Build for ${{ matrix.platform }}
        run: |
          if [ ${{ matrix.platform }} == 'windows' ]; then
            flutter build windows
            elif [ ${{ matrix.platform }} == 'linux' ]; then
            flutter build linux
          fi
          flutter build apk
          flutter build appbundle
