name: Flutter Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++  libgtk-3-dev libsecret-1-dev

      - name: Get dependencies
        run: flutter pub get

      - name: Build for linux
        run: flutter build linux

      - name: Build for android
        run: flutter build apk
